import Head from "next/head";
import PageWrapper from "../components/PageWrapper";

const Home = () => {
  return (
    <PageWrapper
      title="Minecount"
      description="Currently counting 102,483 players across 132 Minecraft servers."
    >
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="initial-scale=1, width=device-width" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </PageWrapper>
  );
};

export default Home;
